apiVersion: apps/v1
kind: Deployment
metadata:
  name: tamasha-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tamasha
  template:
    metadata:
      labels:
        app: tamasha
    spec:
      containers:
      - name: tamasha
        image: lalchandrajak05/task:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tamasha-svc
spec:
  selector:
    app: tamasha
  ports:
    - protocol: TCP
      port: 808
      targetPort: 8080
  type: LoadBalancer
