apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tamasha
  name: tamasha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tamasha
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: tamasha
    spec:
      containers:
      - image: lalchandrajak05/task:latest
        name: tamasha
        imagePullPolicy: Always
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 
        ports:
          - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: tamasha
  labels:
    run: tamasha
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: tamasha
  type: LoadBalancer
